FDO18
git-svn-id: http://svn.osgeo.org/fdo/trunk@2356 d98eaee6-4212-0410-900c-dcc49bf69b99

diff --git a/Providers/ArcSDE/configure b/Providers/ArcSDE/configure
--- a/Providers/ArcSDE/configure
+++ b/Providers/ArcSDE/configure
@@ -8233,7 +8233,7 @@ else
 fi;
 
 if test $custom_fdo = "DEFAULT"; then
-  if test -d $FDO; then
+  if test -d $FDO && test ! $FDO = ""; then
   	{ echo "$as_me:$LINENO: Building with default location of FDO API files at $FDO" >&5
 echo "$as_me: Building with default location of FDO API files at $FDO" >&6;}
   else
@@ -8263,7 +8263,7 @@ else
 fi;
 
 if test $custom_fdo_utilities = "DEFAULT"; then
-  if test -d $FDOUTILITIES; then
+  if test -d $FDOUTILITIES && test ! $FDOUTILITIES = ""; then
   	{ echo "$as_me:$LINENO: Building with default location of FDO Utility files at $FDOUTILITIES" >&5
 echo "$as_me: Building with default location of FDO Utility files at $FDOUTILITIES" >&6;}
   else
@@ -8293,7 +8293,7 @@ else
 fi;
 
 if test $custom_fdo_thirdparty = "DEFAULT"; then
-  if test -d $FDOTHIRDPARTY; then
+  if test -d $FDOTHIRDPARTY && test ! $FDOTHIRDPARTY = ""; then
   	{ echo "$as_me:$LINENO: Building with default location of FDO Thirdparty files at $FDOTHIRDPARTY" >&5
 echo "$as_me: Building with default location of FDO Thirdparty files at $FDOTHIRDPARTY" >&6;}
   else
@@ -8304,8 +8304,8 @@ echo "$as_me: error: The default FDO Thirdparty path $custom_fdo_thirdparty is n
 else
   if test -d $custom_fdo_thirdparty; then
   	FDOTHIRDPARTY="$custom_fdo_thirdparty"
-  	{ echo "$as_me:$LINENO: Building with custom location of FDO Thirdperty directory at $FDOUTILITIES" >&5
-echo "$as_me: Building with custom location of FDO Thirdperty directory at $FDOUTILITIES" >&6;}
+  	{ echo "$as_me:$LINENO: Building with custom location of FDO Thirdperty directory at $FDOTHIRDPARTY" >&5
+echo "$as_me: Building with custom location of FDO Thirdperty directory at $FDOTHIRDPARTY" >&6;}
   else
 	{ { echo "$as_me:$LINENO: error: The specified FDO Thirdparty path $custom_fdo_thirdparty is not a valid directory" >&5
 echo "$as_me: error: The specified FDO Thirdparty path $custom_fdo_thirdparty is not a valid directory" >&2;}
@@ -8323,22 +8323,22 @@ else
 fi;
 
 if test $custom_sde_home = "DEFAULT"; then
-  if test -d $SDEHOME; then
+  if test -d $SDEHOME && test ! $SDEHOME = ""; then
   	{ echo "$as_me:$LINENO: Building with default location of ESRI ArcSDE SDK files at $SDEHOME" >&5
 echo "$as_me: Building with default location of ESRI ArcSDE SDK files at $SDEHOME" >&6;}
   else
- 	{ { echo "$as_me:$LINENO: error: The default ESRI ArcSDE path $custom_sde_home is not a valid directory. Please use the custom option" >&5
-echo "$as_me: error: The default ESRI ArcSDE path $custom_sde_home is not a valid directory. Please use the custom option" >&2;}
+ 	{ { echo "$as_me:$LINENO: error: The default ESRI ArcSDE SDK path $custom_sde_home is not a valid directory. Please use the custom option" >&5
+echo "$as_me: error: The default ESRI ArcSDE SDK path $custom_sde_home is not a valid directory. Please use the custom option" >&2;}
    { (exit 1); exit 1; }; }
   fi
 else
   if test -d $custom_sde_home; then
   	SDEHOME="$custom_sde_home"
-  	{ echo "$as_me:$LINENO: Building with custom location of ESRI ArcSDE SDK directory at $SDEHOME" >&5
-echo "$as_me: Building with custom location of ESRI ArcSDE SDK directory at $SDEHOME" >&6;}
+  	{ echo "$as_me:$LINENO: Building with custom location of ESRI ArcSDE SDK files at $SDEHOME" >&5
+echo "$as_me: Building with custom location of ESRI ArcSDE SDK files at $SDEHOME" >&6;}
   else
-	{ { echo "$as_me:$LINENO: error: The specified FDO Thirdparty path $custom_sde_home is not a valid directory" >&5
-echo "$as_me: error: The specified FDO Thirdparty path $custom_sde_home is not a valid directory" >&2;}
+	{ { echo "$as_me:$LINENO: error: The specified ESRI ArcSDE SDK path $custom_sde_home is not a valid directory" >&5
+echo "$as_me: error: The specified ESRI ArcSDE SDK path $custom_sde_home is not a valid directory" >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
